/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookpublishingcompany.userinterface.realsystem;

import bookpublishingcompany.appicationlogic.customermanagement.Author;
import bookpublishingcompany.appicationlogic.customermanagement.CustomerManager;

import javax.swing.*;
import java.sql.SQLException;

/**
 * @author Disura
 */
public class AddAuthorToBook_1 extends javax.swing.JFrame {

    private String bookName, authorName;
    private int mobileNo;
    private BookCreationUI_1 bookCreationUI_1;

    /**
     * Creates new form SearchAuthorUI
     */
    public AddAuthorToBook_1(BookCreationUI_1 bookCreationUI_1, String bookName) {
        this.bookName = bookName;
        this.bookCreationUI_1 = bookCreationUI_1;
        initComponents();
        searchButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        authorNameText = new javax.swing.JTextField();
        authorNameLabel = new javax.swing.JLabel();
        mobileNoLabel = new javax.swing.JLabel();
        mobileNoText = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Author");

        authorNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorNameTextActionPerformed(evt);
            }
        });

        authorNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        authorNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        authorNameLabel.setText("Name");

        mobileNoLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mobileNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mobileNoLabel.setText("Mobile No");

        mobileNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileNoTextActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    searchButtonActionPerformed(evt);
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(searchButton)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(authorNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(authorNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(mobileNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(mobileNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(authorNameText)
                                        .addComponent(authorNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(mobileNoText)
                                        .addComponent(mobileNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchButton)
                                .addContainerGap(149, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void authorNameTextActionPerformed(java.awt.event.ActionEvent evt) {
        authorName = authorNameText.getText();
        mobileNoText.requestFocus();
    }

    private void mobileNoTextActionPerformed(java.awt.event.ActionEvent evt) {
        mobileNo = Integer.parseInt(mobileNoText.getText());
        searchButton.setEnabled(true);
    }

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {
        authorName = authorNameText.getText();
        mobileNo = Integer.parseInt(mobileNoText.getText());

        CustomerManager customerManager = CustomerManager.getInstance();
        Author author;
        if ((author = customerManager.getAuthor(authorName, mobileNo)) != null) {
            AddAuthorToBook_FoundAuthor ui = new AddAuthorToBook_FoundAuthor(author, this);
            ui.setBookName(bookName);
            ui.setVisible(true);
        } else {
            AddAuthorToBook_AuthorNotFound ui = new AddAuthorToBook_AuthorNotFound();
            ui.setAuthorName(authorName);
            ui.setVisible(true);
        }
    }

    public void addAuthor(Author author, boolean addCondition) {
        if (addCondition) {
            bookCreationUI_1.addAuthor(author);
            this.setVisible(false);
        } else {
            this.setVisible(false);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAuthorToBook_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAuthorToBook_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAuthorToBook_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAuthorToBook_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel authorNameLabel;
    private javax.swing.JTextField authorNameText;
    private javax.swing.JLabel mobileNoLabel;
    private javax.swing.JTextField mobileNoText;
    private javax.swing.JButton searchButton;
    // End of variables declaration
}
