/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookpublishingcompany.userinterface.realsystem;

import javax.swing.*;

/**
 *
 * @author Disura
 */
public class AddAuthorToBook_AuthorNotFound extends javax.swing.JFrame {

    private String authorName;

    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }

    /**
     * Creates new form AddAuthorToBook_AuthorNotFound
     */
    public AddAuthorToBook_AuthorNotFound() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        authorWordLabel = new javax.swing.JLabel();
        authorNameLabel = new javax.swing.JLabel();
        notFoundWordLabel = new javax.swing.JLabel();
        addAuthorQuestionWordLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        authorWordLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        authorWordLabel.setText("Author");

        authorNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        notFoundWordLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        notFoundWordLabel.setText("Not found!");

        addAuthorQuestionWordLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addAuthorQuestionWordLabel.setText("Add New Author?");

        okButton.setText("OK");
        okButton.setToolTipText("");

        cancelButton.setText("Cancel");
        cancelButton.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(authorWordLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(authorNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(notFoundWordLabel)
                                        .addComponent(addAuthorQuestionWordLabel))
                                .addContainerGap(18, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(okButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelButton)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(authorWordLabel)
                                        .addComponent(authorNameLabel))
                                .addGap(18, 18, 18)
                                .addComponent(notFoundWordLabel)
                                .addGap(18, 18, 18)
                                .addComponent(addAuthorQuestionWordLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(okButton)
                                        .addComponent(cancelButton))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAuthorToBook_AuthorNotFound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAuthorToBook_AuthorNotFound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAuthorToBook_AuthorNotFound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAuthorToBook_AuthorNotFound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAuthorToBook_AuthorNotFound().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel addAuthorQuestionWordLabel;
    private javax.swing.JLabel authorNameLabel;
    private javax.swing.JLabel authorWordLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel notFoundWordLabel;
    private javax.swing.JButton okButton;
    // End of variables declaration
}
