/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookpublishingcompany.userinterface.realsystem;

import bookpublishingcompany.appicationlogic.customermanagement.CustomerManager;
import java.awt.Color;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Disura
 */
public class AddNewAuthorUI extends javax.swing.JFrame {

    private HashMap<String, String> authorDetails = new HashMap<>();

    /**
     * Creates new form AddNewAuthor
     */
    public AddNewAuthorUI() {
        initComponents();
        addButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        authorExistsDialog = new javax.swing.JDialog();
        authorExistsLabel = new javax.swing.JLabel();
        successDialog = new javax.swing.JDialog();
        successLabel = new javax.swing.JLabel();
        mobileNoLabel = new javax.swing.JLabel();
        authorNameLabel = new javax.swing.JLabel();
        authorNameText = new javax.swing.JTextField();
        mobileNoText = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();

        authorExistsDialog.setPreferredSize(new java.awt.Dimension(400, 150));
        authorExistsDialog.setSize(new java.awt.Dimension(400, 150));

        authorExistsLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        authorExistsLabel.setText("Author has been already added!");

        javax.swing.GroupLayout authorExistsDialogLayout = new javax.swing.GroupLayout(authorExistsDialog.getContentPane());
        authorExistsDialog.getContentPane().setLayout(authorExistsDialogLayout);
        authorExistsDialogLayout.setHorizontalGroup(
                authorExistsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, authorExistsDialogLayout.createSequentialGroup()
                                .addContainerGap(62, Short.MAX_VALUE)
                                .addComponent(authorExistsLabel)
                                .addGap(51, 51, 51))
        );
        authorExistsDialogLayout.setVerticalGroup(
                authorExistsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(authorExistsDialogLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(authorExistsLabel)
                                .addContainerGap(96, Short.MAX_VALUE))
        );

        successDialog.setPreferredSize(new java.awt.Dimension(400, 150));
        successDialog.setSize(new java.awt.Dimension(400, 150));

        successLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        successLabel.setText("Author successfully added!");

        javax.swing.GroupLayout successDialogLayout = new javax.swing.GroupLayout(successDialog.getContentPane());
        successDialog.getContentPane().setLayout(successDialogLayout);
        successDialogLayout.setHorizontalGroup(
                successDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, successDialogLayout.createSequentialGroup()
                                .addContainerGap(80, Short.MAX_VALUE)
                                .addComponent(successLabel)
                                .addGap(78, 78, 78))
        );
        successDialogLayout.setVerticalGroup(
                successDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(successDialogLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(successLabel)
                                .addContainerGap(100, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add New Author");

        mobileNoLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mobileNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mobileNoLabel.setText("Mobile No");

        authorNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        authorNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        authorNameLabel.setText("Name");

        authorNameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                authorNameTextFocusGained(evt);
            }
        });
        authorNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorNameTextActionPerformed(evt);
            }
        });

        mobileNoText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mobileNoTextFocusGained(evt);
            }
        });
        mobileNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileNoTextActionPerformed(evt);
            }
        });
        mobileNoText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobileNoTextKeyTyped(evt);
            }
        });

        emailLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        emailLabel.setText("Email");

        emailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextActionPerformed(evt);
            }
        });

        addButton.setText("Add Author");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(addButton)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(authorNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(authorNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(mobileNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(mobileNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(authorNameText)
                                        .addComponent(authorNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(mobileNoText)
                                        .addComponent(mobileNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(emailText)
                                        .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(addButton)
                                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void authorNameTextActionPerformed(java.awt.event.ActionEvent evt) {
        if (!authorNameText.getText().equals("")) {
            authorDetails.put("name", authorNameText.getText());
        } else {
            authorNameText.setText("Please give name");
            authorNameText.setForeground(Color.red);
            authorDetails.remove("name");
        }
        mobileNoText.requestFocus();
    }

    private void mobileNoTextActionPerformed(java.awt.event.ActionEvent evt) {
        if (!mobileNoText.getText().equals("")) {
            authorDetails.put("mobileNo", mobileNoText.getText());
            addButton.setEnabled(true);
        } else {
            mobileNoText.setText("Please give mobile number");
            mobileNoText.setForeground(Color.red);
            authorDetails.remove("mobileNo");
        }
        emailText.requestFocus();
    }

    private void mobileNoTextKeyTyped(java.awt.event.KeyEvent evt) {
        addButton.setEnabled(true);
    }

    private void emailTextActionPerformed(java.awt.event.ActionEvent evt) {
        if (!emailText.getText().equals("")) {
            authorDetails.put("email", emailText.getText());
        }
    }

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {
        authorNameTextActionPerformed(evt);
        mobileNoTextActionPerformed(evt);
        emailTextActionPerformed(evt);
        if (authorDetails.keySet().contains("name") && authorDetails.keySet().contains("mobileNo")) {
            CustomerManager customerManager = CustomerManager.getInstance();
            try {
                boolean result = customerManager.addNewAuthor(authorDetails);
                if (result) {
                    successDialog.setVisible(true);
                } else {
                    authorExistsDialog.setVisible(true);
                }
            } catch (SQLException ex) {
                Logger.getLogger(AddNewAuthorUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    private void authorNameTextFocusGained(java.awt.event.FocusEvent evt) {
        authorNameText.setText("");
        authorNameText.setForeground(Color.black);
    }

    private void mobileNoTextFocusGained(java.awt.event.FocusEvent evt) {
        mobileNoText.setText("");
        mobileNoText.setForeground(Color.black);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewAuthorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewAuthorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewAuthorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewAuthorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewAuthorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton addButton;
    private javax.swing.JDialog authorExistsDialog;
    private javax.swing.JLabel authorExistsLabel;
    private javax.swing.JLabel authorNameLabel;
    private javax.swing.JTextField authorNameText;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel mobileNoLabel;
    private javax.swing.JTextField mobileNoText;
    private javax.swing.JDialog successDialog;
    private javax.swing.JLabel successLabel;
    // End of variables declaration
}
