/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookpublishingcompany.userinterface.realsystem;

import bookpublishingcompany.appicationlogic.customermanagement.Author;
import bookpublishingcompany.appicationlogic.publishingprocess.BookManager;
import java.sql.SQLException;

import java.util.ArrayList;

/**
 * @author Disura
 */
public class BookCreationUI_1 extends javax.swing.JFrame {

    private String bookName, dateDue;
    private int version;
    private ArrayList<Author> authorArrayList = new ArrayList<>();
    private ArrayList<String> authorIdList = new ArrayList<>();
    private float totalAmount, advanceAmount;

    public void setDateDue(String dateDue) {
        this.dateDue = dateDue;
    }

    public void setTotalAmount(float totalAmount) {
        this.totalAmount = totalAmount;
    }

    public void setAdvanceAmount(float advanceAmount) {
        this.advanceAmount = advanceAmount;
    }

    /**
     * Creates new form BookCreationUI_1
     */
    public BookCreationUI_1() {
        initComponents();
        nextButton.setEnabled(false);
        addAuthorButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        bookNameText = new javax.swing.JTextField();
        versionLabel = new javax.swing.JLabel();
        versionText = new javax.swing.JTextField();
        authorsLabel = new javax.swing.JLabel();
        addAuthorButton = new javax.swing.JButton();
        author2Label = new javax.swing.JLabel();
        author1Label = new javax.swing.JLabel();
        author3Label = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create New Book");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(500, 400));

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleLabel.setText("Book Title");

        bookNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookNameTextActionPerformed(evt);
            }
        });

        versionLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        versionLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        versionLabel.setText("Version");

        versionText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                versionTextActionPerformed(evt);
            }
        });

        authorsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        authorsLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        authorsLabel.setText("Author(s)");

        addAuthorButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addAuthorButton.setText("Add Author");
        addAuthorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAuthorButtonActionPerformed(evt);
            }
        });

        author2Label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        author2Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        author1Label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        author1Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        author3Label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        author3Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(author1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(author3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(author2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(versionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(authorsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(bookNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(versionText, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(addAuthorButton))))
                                                .addGap(0, 31, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nextButton)
                                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(bookNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                        .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(versionText)
                                        .addComponent(versionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(authorsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addAuthorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(author1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(author2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(author3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(nextButton)
                                .addGap(29, 29, 29))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void bookNameTextActionPerformed(java.awt.event.ActionEvent evt) {
        bookName = bookNameText.getText();
        versionText.requestFocus();
    }

    private void versionTextActionPerformed(java.awt.event.ActionEvent evt) {
        version = Integer.parseInt(versionText.getText());
        addAuthorButton.setEnabled(true);
    }

    private void addAuthorButtonActionPerformed(java.awt.event.ActionEvent evt) {
        bookName = bookNameText.getText();
        version = Integer.parseInt(versionText.getText());
        System.out.println(bookName + " " + version);

        AddAuthorToBook_1 ui = new AddAuthorToBook_1(this, bookName);
        ui.setVisible(true);


    }

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {
        CreateOrderUI createOrderUI = new CreateOrderUI(this);
        createOrderUI.setVisible(true);
    }

    public void addAuthor(Author author) {
        if (!authorIdList.contains(author.getId())) {
            authorArrayList.add(author);
            authorIdList.add(author.getId());
            System.out.println(author1Label.getText());
            if (author1Label.getText().equals("")) {
                author1Label.setText(author.getName());
                nextButton.setEnabled(true);
            } else if (author2Label.getText().equals("")) {
                author2Label.setText(author.getName());
            } else if (author3Label.getText().equals("")) {
                author3Label.setText(author.getName());
                addAuthorButton.setEnabled(false);
            }
        }

    }

    public void completeBookCreation(String dateDue, float totalAmount, float advanceAmount, CreateOrderUI createOrderUI) throws SQLException{
        BookManager bookManager = BookManager.getInstance();
        boolean result = bookManager.createUnpublishedBook(bookName, version, authorArrayList, dateDue, totalAmount, advanceAmount);
        createOrderUI.displayCreationResult(result);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookCreationUI_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookCreationUI_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookCreationUI_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookCreationUI_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookCreationUI_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton addAuthorButton;
    private javax.swing.JLabel author1Label;
    private javax.swing.JLabel author2Label;
    private javax.swing.JLabel author3Label;
    private javax.swing.JLabel authorsLabel;
    private javax.swing.JTextField bookNameText;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel versionLabel;
    private javax.swing.JTextField versionText;
    // End of variables declaration
}
