/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookpublishingcompany.userinterface.realsystem;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sepali
 */
public class CreateOrderUI extends javax.swing.JFrame {
    private String year;
    private String month;
    private String date;
    private String fullAm;
    private String Advance;
    private BookCreationUI_1 bookCreationUI_1;
    /**
     * Creates new form CreateOrderUI
     */
    public CreateOrderUI(BookCreationUI_1 bookCreationUI_1) {
        this.bookCreationUI_1 = bookCreationUI_1;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        failedDialog = new javax.swing.JDialog();
        failedLabel = new javax.swing.JLabel();
        successDialog = new javax.swing.JDialog();
        successLabel = new javax.swing.JLabel();
        DueDateLabel = new javax.swing.JLabel();
        TotalAmountLabel = new javax.swing.JLabel();
        AdvancedAmountLabel = new javax.swing.JLabel();
        CreateButton = new javax.swing.JButton();
        YearText = new javax.swing.JTextField();
        TotalAmountText = new javax.swing.JTextField();
        AdvanceAmountText = new javax.swing.JTextField();
        MonthText = new javax.swing.JTextField();
        DateText = new javax.swing.JTextField();
        YearLabel = new javax.swing.JLabel();
        MonthLabel = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();

        failedDialog.setSize(new java.awt.Dimension(400, 300));

        failedLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        failedLabel.setText("Book creation failed!");

        javax.swing.GroupLayout failedDialogLayout = new javax.swing.GroupLayout(failedDialog.getContentPane());
        failedDialog.getContentPane().setLayout(failedDialogLayout);
        failedDialogLayout.setHorizontalGroup(
                failedDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(failedDialogLayout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(failedLabel)
                                .addContainerGap(108, Short.MAX_VALUE))
        );
        failedDialogLayout.setVerticalGroup(
                failedDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(failedDialogLayout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(failedLabel)
                                .addContainerGap(148, Short.MAX_VALUE))
        );

        successDialog.setSize(new java.awt.Dimension(400, 300));

        successLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        successLabel.setText("Book successfully created!");

        javax.swing.GroupLayout successDialogLayout = new javax.swing.GroupLayout(successDialog.getContentPane());
        successDialog.getContentPane().setLayout(successDialogLayout);
        successDialogLayout.setHorizontalGroup(
                successDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, successDialogLayout.createSequentialGroup()
                                .addContainerGap(83, Short.MAX_VALUE)
                                .addComponent(successLabel)
                                .addGap(78, 78, 78))
        );
        successDialogLayout.setVerticalGroup(
                successDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(successDialogLayout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(successLabel)
                                .addContainerGap(150, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create Order");

        DueDateLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 17)); // NOI18N
        DueDateLabel.setText("Due Date :");

        TotalAmountLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 17)); // NOI18N
        TotalAmountLabel.setText("Total Amount :");

        AdvancedAmountLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 17)); // NOI18N
        AdvancedAmountLabel.setText("Advance Amount : ");

        CreateButton.setFont(new java.awt.Font("Trebuchet MS", 1, 17)); // NOI18N
        CreateButton.setText("Create");
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });

        YearText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearTextActionPerformed(evt);
            }
        });

        TotalAmountText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalAmountTextActionPerformed(evt);
            }
        });

        AdvanceAmountText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdvanceAmountTextActionPerformed(evt);
            }
        });

        MonthText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthTextActionPerformed(evt);
            }
        });

        DateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateTextActionPerformed(evt);
            }
        });

        YearLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        YearLabel.setText("Year :");

        MonthLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        MonthLabel.setText("Month :");

        DateLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        DateLabel.setText("Date :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(DueDateLabel)
                                                        .addComponent(TotalAmountLabel)
                                                        .addComponent(AdvancedAmountLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(162, 162, 162)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(MonthLabel)
                                                                        .addComponent(YearLabel)
                                                                        .addComponent(DateLabel))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(YearText)
                                                                        .addComponent(MonthText)
                                                                        .addComponent(DateText, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(TotalAmountText)
                                                                        .addComponent(AdvanceAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(79, 79, 79))
                                                        .addComponent(CreateButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(DueDateLabel)
                                        .addComponent(YearText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(YearLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(MonthLabel)
                                        .addComponent(MonthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(DateLabel)
                                        .addComponent(DateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TotalAmountLabel)
                                        .addComponent(TotalAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(AdvancedAmountLabel)
                                        .addComponent(AdvanceAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addComponent(CreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        year = YearText.getText();
        month = MonthText.getText();
        date = DateText.getText();
        String dateDue = year + "-" + month + "-" + date;
        fullAm = TotalAmountText.getText();
        Advance = AdvanceAmountText.getText();
        try {
            bookCreationUI_1.completeBookCreation(dateDue, Float.parseFloat(fullAm), Float.parseFloat(Advance), this);
        } catch (SQLException ex) {
            Logger.getLogger(CreateOrderUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void TotalAmountTextActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        AdvanceAmountText.requestFocus();
    }

    private void YearTextActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        MonthText.requestFocus();
    }

    private void MonthTextActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        DateText.requestFocus();
    }

    private void DateTextActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        TotalAmountText.requestFocus();
    }

    private void AdvanceAmountTextActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        CreateButton.requestFocus();
    }


    public void displayCreationResult(boolean result){
        this.setVisible(false);
        if (result) {
            successDialog.setVisible(true);
        } else {
            failedDialog.setVisible(true);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateOrderUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateOrderUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateOrderUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateOrderUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JTextField AdvanceAmountText;
    private javax.swing.JLabel AdvancedAmountLabel;
    private javax.swing.JButton CreateButton;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JTextField DateText;
    private javax.swing.JLabel DueDateLabel;
    private javax.swing.JLabel MonthLabel;
    private javax.swing.JTextField MonthText;
    private javax.swing.JLabel TotalAmountLabel;
    private javax.swing.JTextField TotalAmountText;
    private javax.swing.JLabel YearLabel;
    private javax.swing.JTextField YearText;
    private javax.swing.JDialog failedDialog;
    private javax.swing.JLabel failedLabel;
    private javax.swing.JDialog successDialog;
    private javax.swing.JLabel successLabel;
    // End of variables declaration
}
